### PR TITLE
Refactoring: Menu Repository

### PR DESCRIPTION
**Pull request by lbajsarowicz**
1. `$model->save()` and `$model->delete()` breaks SOLID principle of single responsibility. Although it's not introduced to Coding Standard yet, the Resource Model should be used for operating with the database. https://github.com/magento/magento-coding-standard/issues/187
2. Add Exceptions to the interface, as these are part of interface API.
3. Improve verbosity and readability of the Repository (`Object` - > `Menu` etc.)

### CODE REVIEW

**Comment by Igloczek** [comment]
Internal ticket DEV-69361

**Comment by TM18** [comment]
@lbajsarowicz was this ticket closed on purpose?

**Comment by lbajsarowicz** [comment]
A month passed by without any feedback.
I'm going to fork and develop the MegaMenu on my own.

**Comment by mcjwsk** [comment]
Łukasz, please don't be offended! We are glad to see your pull requests. We promise improvement. Lets develop the module together.

**Comment by lbajsarowicz** [comment]
No emotions involved. It's just maintainability as I regularly review all my PRs to check the progress.
If you like - just do the Cherry Pick and proceed, I need to have an easy way to extend your module, but to be able to do so - I need to clean up the rubbish that is already there. When reviewing cleanup takes > 30 days, it's going to take months to introduce serious changes to the code.

**Comment by mcjwsk** [comment]
Okay, seems reasonable, but give us a second chance. I appreciate your involvement and I want to have you as a contributor here :).

**Comment by lbajsarowicz** [comment]
giphy

Don't make it hang too long.

**Review by TM18 — APPROVED** [review]

**Pull request merged**
