### PR TITLE
[74936] Fix custom templates for node types wrapper and custom_url

### PR DESCRIPTION
**Pull request by thampe**
Hi,

first of all thanks for providing this extension!

This PR provides a fix for the custom template features on the node types `wrapper` and `custom_url`.

### CODE REVIEW

**Comment by andrzejborkowski** [comment]
Thank you for reporting and fixing the issue, we'll review your PR soon

**Comment by akai-z** [comment]
I checked the fix and it worked properly.

But I found that `snowMenuSimpleField` data was not used anywhere in Vue.js files, thus it did not seem necessary.  
We need a frontend developer to verify that before removing it.

(I applied some minor code changes.)

**Review by akai-z — COMMENTED** [review]
I checked the fix and it worked properly. (I applied some minor code changes.)

But I found that `snowMenuSimpleField` data was not used anywhere in Vue.js files, thus it did not seem necessary.  
We need a frontend developer to verify that before removing it.

**Review by akai-z — CHANGES_REQUESTED** [review]
I found that `snowMenuSimpleField` data (which existed before the fix in this pull request) was not used anywhere in Vue.js files,  
thus it did not seem necessary.

We need a frontend developer to verify that, before removing it.

**Review by akai-z — DISMISSED** [review]

**Review by akai-z — APPROVED** [review]

**Pull request merged**
