### PR TITLE
[74222] Added missed configuration for child category type node.

### PR DESCRIPTION
**Pull request by vmalyk**
Fix for #152.

### CODE REVIEW

**Review by anqaka — APPROVED** [review]
Changes are ok.

**Comment by vmalyk** [comment]
@anqaka , do you resolve conflicts in CHANGELOG.md or is it require to fix from my side?

**Comment by davidwindell** [comment]
LGTM!

**Review by anqaka — APPROVED** [review]

**Comment by anqaka** [comment]
@vmalyk sorry for late action, I was out for a week. Changes merged to develop

**Pull request merged**
