### PR TITLE
Feature: Validate only changed files, display errors inline

### PR DESCRIPTION
**Pull request by lbajsarowicz**
I modified some PHP file introducing some issue that is reported by PHPCS.

Also:
1. Checkout only `depth = 1` to reduce the cost of pulling recent changes
2. Migrated your Composer configuration
3. Introduced Composer cache
4. Executing only on modified files

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
I couldn't force Github to run my `backend.yml` file from my own branch (it still uses `pull_request_target` as a source of tests).

**Comment by Igloczek** [comment]
@lbajsarowicz do you know why it fails without throwing any error?
https://github.com/SnowdogApps/magento2-menu/runs/1030198800?check_suite_focus=true

**Comment by lbajsarowicz** [comment]
@Igloczek I'm going to submit some failing file to check this on real changes. Then it should work, as it failed due to no files provided.

**Comment by Igloczek** [comment]
It was working only for `pull_request` events, but not `push` due to `only_changed_files` option (on push there is no way to build a list of changed files, because is probably compare branches).

**Comment by lbajsarowicz** [comment]
Actually it's written the way that it checks what the Push belongs to and fetches the changed files for all the PR:

https://github.com/Mediotype/phpcs-action/blob/980dd952ece08ad1a1baca4447df4a50ca4d7cd6/entrypoint.sh#L8-L13

I've been using that successfully on other projects.

**Comment by Igloczek** [comment]
Weird :( It stops silently failing after switching that off.

**Pull request merged**
