### PR TITLE
Various php 8.2 fixes

### PR DESCRIPTION
**Pull request by WouterSteen**

### CODE REVIEW

**Comment by WouterSteen** [comment]
Ohw wait a minute, i have a few more :)

**Comment by WouterSteen** [comment]
Yes! All done :)

**Review by jochhop — APPROVED** [review]

**Comment by jochhop** [comment]
Thanks a lot for your contribution @WouterSteen ! your changes have been accepted and merged to develop, they'll be also available in the next menu's release version.

Have a great day!

**Comment by RakeshJesadiya** [comment]
@jochhop When will you release the next version that will be compatible with PHP 8.2? I have seen you have fixed the issue and deployed the changes to develop branch.

**Comment by andrzejborkowski** [comment]
Hey @RakeshJesadiya I expect to get 2.21.0 version released in the next 1-2 weeks

**Comment by andrzejborkowski** [comment]
@RakeshJesadiya FYI we've released 2.21.0 menu module version https://github.com/SnowdogApps/magento2-menu/tree/2.21.0 which is compatible with PHP8.2 now

**Pull request merged**
